import React,{useEffect,useRef,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import type {ArtifactPreview} from './types';
export function ArtifactViewer({preview,path,taskId,onChanged,onRequest}:{preview:ArtifactPreview;path:string;taskId:string;onChanged:()=>void;onRequest:(text:string)=>void}){
 const [editing,setEditing]=useState(false),[text,setText]=useState(preview.content),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sheet,setSheet]=useState(preview.sheets?.[0]?.name||''),[address,setAddress]=useState('A1'),[value,setValue]=useState(''),[feedback,setFeedback]=useState(''),[selection,setSelection]=useState('');const area=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null);const [page,setPage]=useState(1),[pages,setPages]=useState(1);
 useEffect(()=>{setText(preview.content);setEditing(false);setSelection('');setError('');setSheet(preview.sheets?.[0]?.name||'');setPage(1);},[path,preview.version]);
 useEffect(()=>{if(preview.kind!=='pdf')return;let stopped=false;let doc:any,render:any,loadingTask:any;const loading=import('pdfjs-dist').then(async pdf=>{pdf.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).href;const bytes=Uint8Array.from(atob(preview.content),c=>c.charCodeAt(0));loadingTask=pdf.getDocument({data:bytes});doc=await loadingTask.promise;if(stopped){await loadingTask.destroy();return;}setPages(doc.numPages);const p=await doc.getPage(page);if(stopped)return;const view=p.getViewport({scale:1});const c=canvas.current;if(c){c.width=view.width;c.height=view.height;render=p.render({canvas:c,viewport:view});await render.promise;}}).catch(e=>{if(!stopped)setError(String(e));});return()=>{stopped=true;render?.cancel();void loading.then(()=>loadingTask?.destroy());};},[preview.kind,preview.version,page]);
 async function save(operation?:string){setBusy(true);setError('');try{await window.ailo.editArtifact(taskId,path,{version:preview.version,operation,text:preview.kind==='spreadsheet'?value:text,sheet,address});onChanged();setEditing(false);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="artifact-viewer"><div ref={area} onMouseUp={()=>{const s=window.getSelection();if(s?.anchorNode&&area.current?.contains(s.anchorNode))setSelection(s.toString().slice(0,10000));}}>
 {preview.kind==='image'?<img alt={path} src={preview.content}/>:preview.kind==='pdf'?<><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page} / {pages} 页</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>下一页</button><canvas ref={canvas} style={{maxWidth:'100%'}}/></>:preview.kind==='html'?<iframe title={path} sandbox="" referrerPolicy="no-referrer" srcDoc={'<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:;">'+preview.content} style={{width:'100%',minHeight:420,border:0}}/>:preview.kind==='spreadsheet'?<><select value={sheet} onChange={e=>setSheet(e.target.value)}>{preview.sheets?.map(s=><option key={s.name}>{s.name}</option>)}</select><table><thead><tr><th>单元格</th><th>内容</th></tr></thead><tbody>{preview.sheets?.find(s=>s.name===sheet)?.cells.map(c=><tr key={c.address} onClick={()=>{setAddress(c.address);setValue(c.text);setSelection(`${sheet}!${c.address}: ${c.text}`);}}><td>{c.address}</td><td>{c.text}</td></tr>)}</tbody></table><label>单元格<input value={address} onChange={e=>setAddress(e.target.value.toUpperCase())}/></label><label>新文本值<input value={value} onChange={e=>setValue(e.target.value)}/></label><p className="muted">保存文本值会替换该单元格原有公式，不会重算其他公式。</p><button disabled={busy} onClick={()=>void save()}>保存单元格</button></>:editing?<textarea rows={16} value={text} onChange={e=>setText(e.target.value)}/>:preview.kind==='markdown'?<ReactMarkdown skipHtml components={{a:({href,children})=><a href={href} onClick={e=>{e.preventDefault();if(href&&/^https?:\/\//.test(href))void window.ailo.openWeb(href);}}>{children}</a>,img:()=>null}}>{preview.content}</ReactMarkdown>:<pre>{preview.content}</pre>}
 </div>{!preview.truncated&&/\.(md|markdown|txt|csv|tsv)$/i.test(path)&&<><button disabled={busy} onClick={()=>setEditing(v=>!v)}>{editing?'取消编辑':'编辑文字'}</button>{editing&&<button disabled={busy} onClick={()=>void save()}>保存修改</button>}</>}{/\.(md|markdown|txt|csv|tsv|xlsx)$/i.test(path)&&<button disabled={busy} onClick={()=>void save('restore')}>恢复上一版本</button>}
 <label>让 Ailo 修改<textarea rows={3} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="说明希望修改的内容；可先选中文字或点击单元格"/></label>{selection&&<p className="muted">已引用：{selection.slice(0,180)}</p>}<button disabled={!feedback.trim()} onClick={()=>onRequest(`请修改项目文件 ${JSON.stringify(path)}。预览版本 SHA-256：${preview.version}。${preview.kind==='pdf'?`反馈位置：第 ${page} 页；请修改源文档后重新导出 PDF。`:''}${selection?`引用区域：${JSON.stringify(selection)}。`:''}修改要求：${feedback}。请先读取当前文件，确认引用位置与版本；保存修改前版本，仅修改要求的内容，并重新验证和登记成果。`)}>带入对话</button>{error&&<p className="error" role="alert">{error}</p>}</div>;
}
