import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './icon';
import type {Extension} from './types';
type Category='expert'|'skill'|'connector';
export function ComposerAdd({items,value,disabled,importing,onChange,onAttach,onManage,onDefault,feishu,setFeishu,onProject,onKnowledge,searchEnabled,setSearchEnabled}:{onKnowledge?:(anchor:HTMLButtonElement)=>void;searchEnabled:boolean;setSearchEnabled:(value:boolean)=>void;onProject?:(anchor:HTMLButtonElement)=>void;feishu:boolean;setFeishu:(value:boolean)=>void;items:Extension[];value:string[];disabled:boolean;importing:boolean;onChange:(ids:string[])=>void;onAttach:()=>void;onManage:(tab:Category)=>void;onDefault?:()=>void}){
 const [open,setOpen]=useState(false),[category,setCategory]=useState<Category|null>(null),[query,setQuery]=useState(''),[connected,setConnected]=useState(false),[checking,setChecking]=useState(false);
 const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const close=()=>{setOpen(false);setCategory(null);setQuery('');trigger.current?.focus();};
 useEffect(()=>{if(!open)return;const click=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))close();};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',key);};},[open]);
 useEffect(()=>{if(!open||category!=='connector')return;let alive=true;setChecking(true);window.ailo.feishuCliStatus().then(s=>{if(alive){setConnected(s.connected);if(!s.connected)setFeishu(false);}}).catch(()=>{if(alive)setConnected(false);}).finally(()=>{if(alive)setChecking(false);});return()=>{alive=false;};},[open,category]);
 const [searchReady,setSearchReady]=useState(false);
 useEffect(()=>{if(!open||category!=='connector')return;let alive=true;window.ailo.searchStatus().then(s=>{if(alive)setSearchReady(s.connected);}).catch(()=>{if(alive)setSearchReady(false);});return()=>{alive=false;};},[open,category]);
 const selected=items.filter(i=>value.includes(i.id));
 function toggle(item:Extension){if(value.includes(item.id))onChange(value.filter(id=>id!==item.id));else onChange([...value.filter(id=>item.kind!=='expert'||items.find(i=>i.id===id)?.kind!=='expert'),item.id]);}
 return <div className="composer-add" ref={root}>
  <button ref={trigger} type="button" className="composer-add-trigger" aria-label="添加文件、项目、专家、技能或应用连接或知识库" aria-haspopup="dialog" aria-expanded={open} disabled={disabled} onClick={()=>{if(open)close();else setOpen(true);}} title="添加"><Icon name="plus"/></button>
  {importing&&<span className="composer-add-reading">正在读取…</span>}
  {selected.map(i=><button type="button" className="composer-add-chip" key={i.id} disabled={disabled} title={'移除'+i.name} onClick={()=>onChange(value.filter(id=>id!==i.id))}>{i.name}<span aria-hidden="true"> ×</span></button>)}
  {searchEnabled&&<button type="button" className="composer-add-chip" title="关闭当前对话的联网搜索" onClick={()=>setSearchEnabled(false)}>◎ 联网搜索 ×</button>}
  {feishu&&<button type="button" className="composer-add-chip" title="关闭当前对话的飞书连接（不解绑账号）" onClick={()=>setFeishu(false)}><img src="./feishu.png" alt="飞书"/><span aria-hidden="true">×</span></button>}
  {open&&<div className="composer-add-popover" role="dialog" aria-label="添加到对话">
   {!category?<>{onProject&&<button type="button" className="composer-add-row" disabled={disabled} onClick={()=>{const anchor=trigger.current;close();if(anchor)onProject(anchor);}}><Icon name="folder"/>项目<span className="composer-add-chevron" aria-hidden="true"><Icon name="chevron-right"/></span></button>}{onKnowledge&&<button type="button" className="composer-add-row" disabled={disabled} onClick={()=>{const anchor=trigger.current;close();if(anchor)onKnowledge(anchor);}}><Icon name="book"/>知识库<span className="composer-add-chevron" aria-hidden="true"><Icon name="chevron-right"/></span></button>}{([['file','paperclip','添加文件'],['expert','user','专家'],['skill','sparkles','技能'],['connector','plug','应用连接']] as const).map(([kind,icon,label])=><button type="button" className="composer-add-row" key={kind} disabled={disabled||kind==='file'&&importing} onClick={()=>{if(kind==='file'){close();onAttach();}else{setCategory(kind);setQuery('');}}}><Icon name={icon}/>{label}<span className="composer-add-chevron" aria-hidden="true"><Icon name="chevron-right"/></span></button>)}</>:<>
    <div className="composer-add-heading"><button type="button" aria-label="返回添加菜单" onClick={()=>{setCategory(null);setQuery('');}}>‹</button><strong>{category==='expert'?'专家':category==='skill'?'技能':'应用连接'}</strong><button type="button" onClick={()=>{const tab=category;close();onManage(tab);}}>管理</button></div>
    {category!=='connector'?<><input autoFocus aria-label="搜索专家或技能" placeholder="搜索名称或用途…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="composer-add-options">{items.filter(i=>i.enabled&&i.kind===category&&(i.name+i.description).toLowerCase().includes(query.toLowerCase())).map(i=><button type="button" key={i.id} aria-pressed={value.includes(i.id)} disabled={disabled||i.kind==='skill'&&!value.includes(i.id)&&selected.filter(x=>x.kind==='skill').length>=5} onClick={()=>toggle(i)}><span>{i.name}<small>{i.description}</small></span><span aria-hidden="true">{value.includes(i.id)?'✓':'＋'}</span></button>)}</div><p>可选 1 位专家和最多 5 个技能</p>{onDefault&&<button type="button" onClick={()=>{onDefault();close();}}>设为项目默认</button>}</>:<><div className="composer-connection-row"><img src="./feishu.png" alt=""/><span>飞书</span>{connected?<button type="button" role="switch" aria-label="在当前对话中使用飞书" aria-checked={feishu} disabled={checking||disabled} className="connection-switch" onClick={()=>setFeishu(!feishu)}><span/></button>:<button type="button" disabled={checking||disabled} onClick={()=>{close();onManage('connector');}}>{checking?'检测中':'去连接'}</button>}</div><div className="composer-connection-row"><span aria-hidden="true">◎</span><span>联网搜索</span>{searchReady?<button type="button" role="switch" aria-label="在当前对话中使用联网搜索" aria-checked={searchEnabled} disabled={disabled} className="connection-switch" onClick={()=>setSearchEnabled(!searchEnabled)}><span/></button>:<button type="button" onClick={()=>{close();onManage('connector');}}>去连接</button>}</div><p>开关仅影响当前对话，不会解绑账号。</p></>}
   </>}
  </div>}
 </div>;
}
