import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {KnowledgeLibrary,KnowledgeHit,KnowledgePage} from './types';
import {Icon} from './icon';
import './knowledge.css';
export function KnowledgeCenter({onUse}:{onUse:(id:string)=>void}){
 const [libraries,setLibraries]=useState<KnowledgeLibrary[]>([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[hits,setHits]=useState<KnowledgeHit[]|null>(null),[page,setPage]=useState<KnowledgePage|null>(null);
 const preview=useRef<HTMLDialogElement>(null);const lib=libraries.find(l=>l.id===selected);
 async function refresh(){const rows=await window.ailo.knowledgeList();setLibraries(rows);setSelected(id=>rows.some(l=>l.id===id)?id:rows[0]?.id||'');}
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(String(e).replace(/^.*Error: /,''));}finally{setBusy(false);}}
 async function open(libraryId:string,documentId:string,offset=0){const result=await window.ailo.knowledgeRead({libraryId,documentId,offset});setPage(result);if(!preview.current?.open)preview.current?.showModal();}
 return <div className="knowledge-center"><div className="extension-heading"><span className="eyebrow">你的长期参考资料</span><h1>知识库</h1><p>整理常用资料，在不同对话中复用。回答可追溯到文件和原文片段。</p></div>
 <div className="knowledge-toolbar"><button className="primary" disabled={busy} onClick={()=>{setEditing(null);setName('');setDescription('');setForm(true);}}>＋ 新建知识库</button><span>{libraries.length} 个知识库</span></div>
 {form&&<form className="extension-editor" onSubmit={e=>{e.preventDefault();void run(async()=>{const saved=await window.ailo.knowledgeSave({id:editing||undefined,name,description});await refresh();setSelected(saved.id);setForm(false);});}}><h2>{editing?'编辑知识库':'新建知识库'}</h2><label>名称<input aria-label="知识库名称" required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>用途说明<input aria-label="知识库用途说明" maxLength={500} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="extension-actions"><button className="primary" disabled={busy}>保存</button><button type="button" disabled={busy} onClick={()=>setForm(false)}>取消</button></div></form>}
 {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}
 {!libraries.length&&!form&&<div className="knowledge-empty"><Icon name="book"/><h2>把常用资料放在这里</h2><p>创建一个知识库，例如“产品资料”或“工作规范”，再导入 DOCX、Markdown 和文本文件。</p></div>}
 {!!libraries.length&&<div className="knowledge-layout"><aside className="knowledge-libraries" aria-label="知识库列表">{libraries.map(l=><button key={l.id} aria-pressed={selected===l.id} onClick={()=>{setSelected(l.id);setHits(null);setQuery('');}}><Icon name="book"/><span>{l.name}<small>{l.documents.length} 份资料</small></span></button>)}</aside>
 {lib&&<section className="knowledge-content"><div className="knowledge-title"><div><h2>{lib.name}</h2><p>{lib.description||'添加资料后，在对话中选择此知识库即可使用。'}</p></div><button disabled={busy} onClick={()=>onUse(lib.id)}>在对话中使用 ↗</button></div>
 <div className="knowledge-toolbar"><button className="primary" disabled={busy} onClick={()=>void run(async()=>{const results=await window.ailo.knowledgeImport(lib.id);await refresh();setHits(null);if(results.length)setMessage(results.map(r=>`${r.name}：${r.status==='imported'?'已导入':r.status==='duplicate'?'内容重复，已跳过':r.error}`).join('；'));})}>{busy?'正在处理…':'导入资料'}</button><button disabled={busy} onClick={()=>{setEditing(lib.id);setName(lib.name);setDescription(lib.description);setForm(true);}}>编辑</button><button disabled={busy} onClick={()=>void run(async()=>{if(await window.ailo.knowledgeRemove(lib.id)){await refresh();setHits(null);}})}>删除知识库</button></div>
 <p className="knowledge-note">支持 DOCX 和 UTF-8 文本，单文件最多 20 MB。资料保存在本机，检索到的片段会发送给当前模型服务。PDF、图片暂不支持。</p>
 <form className="knowledge-search" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await window.ailo.knowledgeSearch({libraryIds:[lib.id],query});setHits(r.hits);setMessage(`找到 ${r.hits.length} 个相关片段，可点击查看原文。`);});}}><input aria-label="搜索知识库资料" placeholder="输入关键词，查找原文…" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy||!query.trim()}>搜索</button></form>
 {hits!==null?<div className="knowledge-results">{!hits.length?<p>没有命中片段，试试其他关键词或直接查看资料。</p>:hits.map(h=><button key={h.documentId+':'+h.offset} onClick={()=>void run(()=>open(h.libraryId,h.documentId,h.offset))}><strong>{h.name} · 片段 {h.chunk}</strong><p>{h.text}</p><small>查看原文 ↗</small></button>)}</div>:<div className="knowledge-documents">{!lib.documents.length?<p className="knowledge-empty">还没有资料，导入文件后即可搜索和引用。</p>:lib.documents.map(d=><article key={d.id}><Icon name="file"/><button className="knowledge-document-name" onClick={()=>void run(()=>open(lib.id,d.id))}><strong>{d.name}</strong><small>{d.chars.toLocaleString()} 字符 · {d.chunks} 个片段 · {new Date(d.createdAt).toLocaleDateString()}</small></button><button disabled={busy} aria-label={`删除资料 ${d.name}`} onClick={()=>void run(async()=>{await window.ailo.knowledgeRemoveDocument({libraryId:lib.id,documentId:d.id});await refresh();})}><Icon name="trash"/></button></article>)}</div>}
 </section>}</div>}
 <dialog className="knowledge-preview" ref={preview} aria-label="知识库原文预览"><div className="knowledge-title"><h2>{page?.name}</h2><button aria-label="关闭原文预览" onClick={()=>preview.current?.close()}>×</button></div><p>{page?.citation} · 共 {page?.total.toLocaleString()} 字符</p><pre>{page?.text}</pre><div className="knowledge-toolbar"><button disabled={busy||!page||page.offset===0} onClick={()=>page&&void run(()=>open(page.libraryId,page.documentId,Math.max(0,page.offset-6000)))}>上一段</button><button disabled={busy||!page||page.next===null} onClick={()=>page?.next!==null&&page&&void run(()=>open(page.libraryId,page.documentId,page.next!))}>下一段</button></div></dialog>
 </div>;
}
export function KnowledgePicker({value,onChange,disabled,onManage,openFrom,onClose}:{openFrom?:HTMLButtonElement|null;onClose?:()=>void;value:string[];onChange:(ids:string[])=>void;disabled:boolean;onManage:()=>void}){
 const [libraries,setLibraries]=useState<KnowledgeLibrary[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false),[position,setPosition]=useState({left:16,top:16,width:300,maxHeight:350});
 const trigger=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null);
 const close=()=>{setOpen(false);onClose?.();};
 useEffect(()=>{if(openFrom)setOpen(true);},[openFrom]);
 useEffect(()=>{let alive=true;window.ailo.knowledgeList().then(rows=>{if(alive)setLibraries(rows);}).catch(()=>{if(alive)setError('知识库列表读取失败');});return()=>{alive=false;};},[open]);
 useLayoutEffect(()=>{
  if(!open)return;
  function place(){const anchor=openFrom||trigger.current;if(!anchor||!popup.current)return;const rect=anchor.getBoundingClientRect(),width=Math.min(320,innerWidth-32),above=rect.top-24,below=innerHeight-rect.bottom-24,maxHeight=Math.min(350,Math.max(above,below)),height=Math.min(popup.current.scrollHeight,maxHeight);setPosition({left:Math.max(16,Math.min(rect.left,innerWidth-width-16)),top:below>=height?rect.bottom+8:Math.max(16,rect.top-height-8),width,maxHeight});}
  place();const observer=new ResizeObserver(place);if(popup.current)observer.observe(popup.current);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{observer.disconnect();window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};
 },[open,openFrom]);
 useEffect(()=>{if(!open)return;function outside(e:PointerEvent){const node=e.target as Node;if(!popup.current?.contains(node)&&!trigger.current?.contains(node)&&!openFrom?.contains(node))close();}function key(e:KeyboardEvent){if(e.key==='Escape'){close();(openFrom||trigger.current)?.focus();}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);popup.current?.querySelector<HTMLInputElement>('input')?.focus();return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key);};},[open,openFrom]);
 return <div className="knowledge-picker">{value.length>0&&<button ref={trigger} type="button" className="knowledge-picker-trigger" disabled={disabled} aria-label="选择知识库" aria-expanded={open} onClick={()=>open?close():setOpen(true)}><Icon name="book"/>知识库{value.length?` · ${value.length}`:''}</button>}
 {value.map(id=><button type="button" className="knowledge-selected" key={id} disabled={disabled} aria-label={`移除知识库 ${libraries.find(l=>l.id===id)?.name||'已删除的知识库'}`} onClick={()=>onChange(value.filter(x=>x!==id))}><span>{libraries.find(l=>l.id===id)?.name||'已删除的知识库'}</span><Icon name="close"/></button>)}
 {open&&createPortal(<div ref={popup} className="knowledge-picker-menu" role="dialog" aria-label="选择对话知识库" style={position}><div className="knowledge-picker-heading"><strong>当前对话的参考资料</strong><button type="button" aria-label="关闭知识库选择" onClick={()=>{close();(openFrom||trigger.current)?.focus();}}><Icon name="close"/></button></div><p>只检索已选择的库，最多 5 个。</p>{libraries.map(l=><label key={l.id}><input type="checkbox" disabled={disabled||(!value.includes(l.id)&&value.length>=5)} checked={value.includes(l.id)} onChange={()=>onChange(value.includes(l.id)?value.filter(id=>id!==l.id):[...value,l.id])}/><span>{l.name}<small>{l.documents.length} 份资料</small></span></label>)}{!libraries.length&&<p>还没有知识库，先添加常用资料。</p>}{error&&<p role="alert">{error}</p>}<div className="extension-actions"><button type="button" disabled={disabled||!value.length} onClick={()=>onChange([])}>清空选择</button><button type="button" onClick={()=>{close();onManage();}}>管理知识库</button></div></div>,document.body)}</div>;
}
