import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './icon';
import type {ConnectionTarget,MCPConnection,MCPConnectionInput,MCPPermission} from './types';
const blank:MCPConnectionInput={name:'',description:'',url:'',authType:'none',headerName:'Authorization',token:'',clientId:''};
export function MCPConnections({query,onState,onTry}:{query:string;onState:(count:number)=>void;onTry:(text:string,target:ConnectionTarget)=>void}) {
 const [servers,setServers]=useState<MCPConnection[]>([]),[selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<MCPConnectionInput>(blank),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),mounted=useRef(true);
 async function refresh(){const list=await window.ailo.mcpList();if(mounted.current){setServers(list);onState(list.filter(s=>s.connected).length);}}
 useEffect(()=>{mounted.current=true;void refresh().catch(()=>setError('无法读取自定义连接'));return()=>{mounted.current=false;};},[]);
 const current=servers.find(s=>s.id===selected);
 function open(server?:MCPConnection){setSelected(server?.id||null);setDraft(server?{id:server.id,name:server.name,description:server.description,url:server.url,authType:server.authType,headerName:server.headerName,clientId:server.clientId,token:''}:{...blank});setError('');setMessage('');dialog.current?.showModal();}
 async function run(fn:()=>Promise<unknown>,success:string){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);}catch(e){setError(String(e).replace(/^.*Error: /,''));}finally{try{await refresh();window.dispatchEvent(new Event('ailo:mcp-changed'));}catch{setError('无法刷新连接状态，请重新打开应用连接。');}setBusy(false);}}
 async function save(){const saved=await window.ailo.mcpSave(draft);setSelected(saved.id);setDraft(d=>({...d,id:saved.id,token:''}));if(saved.authType==='oauth')await window.ailo.mcpAuthorize(saved.id);else await window.ailo.mcpTest(saved.id);}
 const visible=servers.filter(s=>(s.name+' '+s.description+' '+s.url).toLowerCase().includes(query.trim().toLowerCase()));
 return <section className="mcp-center" aria-label="自定义应用连接">
  <div className="mcp-heading"><div><h2>自定义连接</h2><p>接入你使用的工具和资料服务，在对话中按需选择。</p></div><button type="button" className="primary" onClick={()=>open()}>添加自定义 MCP</button></div>
  <div className="connection-grid">{visible.map(s=><article key={s.id} className={'connection-tile '+(s.connected?'is-connected':'')}><button type="button" className="connection-tile-main" aria-label={'管理连接 '+s.name} onClick={()=>open(s)}><span className="connection-tile-heading"><Icon name="plug"/><strong>{s.name}</strong>{s.connected&&<span className="connection-dot" role="img" aria-label={s.name+'已连接'}/>}</span><span className="connection-tile-description">{s.description||'在对话中调用此应用提供的工具。'}</span><span className="connection-tile-status">{s.connected?`已连接 · ${s.tools.filter(t=>t.permission!=='disabled').length} 个工具`:s.error?'连接异常':s.enabled?'等待连接测试':'已断开'}</span></button><button type="button" className="connection-tile-action" aria-label={'配置 '+s.name} onClick={()=>open(s)}>⚙</button></article>)}</div>
  {!servers.length&&<p className="extension-note">已有 MCP 服务地址？添加连接并测试后，即可在对话中使用。</p>}
  {!!servers.length&&!visible.length&&<p className="extension-note">没有匹配的自定义连接。</p>}
  {error&&!dialog.current?.open&&<p className="error" role="alert">{error}</p>}
  <dialog ref={dialog} className="connection-dialog mcp-dialog" aria-label="自定义 MCP 连接管理" onCancel={e=>{if(busy)e.preventDefault();}} onClick={e=>{if(!busy&&e.target===e.currentTarget)dialog.current?.close();}}>
   <div className="connection-dialog-toolbar"><button type="button" className="connection-dialog-close" disabled={busy} aria-label="关闭自定义连接设置" onClick={()=>dialog.current?.close()}>×</button></div>
   <article className="search-settings"><h2>{current?current.name:'添加自定义 MCP'}</h2><p>填写服务提供方的 Streamable HTTP 地址，连接后查看可用工具。</p>
    <form onSubmit={e=>{e.preventDefault();void run(save,draft.authType==='oauth'?'授权及连接测试成功':'连接测试成功');}}>
     <label>应用名称<input aria-label="MCP 应用名称" required maxLength={60} disabled={busy} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
     <label>用途说明<input aria-label="MCP 用途说明" maxLength={300} disabled={busy} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
     <label>服务地址<input aria-label="MCP 服务地址" type="url" required maxLength={2000} disabled={busy} placeholder="https://example.com/mcp" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label>
     <label>认证方式<select aria-label="MCP 认证方式" disabled={busy} value={draft.authType} onChange={e=>setDraft({...draft,authType:e.target.value as MCPConnectionInput['authType'],token:''})}><option value="none">无需认证</option><option value="token">Token / API Key</option><option value="oauth">浏览器授权（OAuth）</option></select></label>
     {draft.authType==='token'&&<><label>Token / API Key<input aria-label="MCP Token" type="password" autoComplete="new-password" disabled={busy} value={draft.token||''} placeholder={current?.hasCredential?'留空保留原服务凭据':'填写服务提供的 Token'} onChange={e=>setDraft({...draft,token:e.target.value})}/></label><details><summary>认证请求头</summary><label>请求头名称<input aria-label="MCP 认证请求头" disabled={busy} value={draft.headerName||'Authorization'} onChange={e=>setDraft({...draft,headerName:e.target.value})}/></label><p className="extension-note">默认使用 Bearer Token；API Key 服务可按说明填写 X-API-Key 等请求头名称。</p></details></>}
     {draft.authType==='oauth'&&<><label>OAuth Client ID（可选）<input aria-label="MCP OAuth Client ID" disabled={busy} value={draft.clientId||''} onChange={e=>setDraft({...draft,clientId:e.target.value})} placeholder="支持自动注册的服务可留空"/></label><p className="extension-note">在浏览器完成授权后返回 Ailo。支持 PKCE 公共客户端；服务不支持自动注册时，请填写其提供的 Client ID。</p></>}
     <p className="extension-note">凭据加密保存在本机，不提供给模型。连接不会自动在所有对话中启用。</p>
     <div className="extension-actions"><button className="primary" disabled={busy}>{busy?'正在连接或等待授权…':draft.authType==='oauth'?'保存并授权':'保存并测试'}</button>{current&&<><button type="button" disabled={busy||!current.enabled||current.authType!=='none'&&!current.hasCredential} onClick={()=>void run(()=>window.ailo.mcpTest(current.id),'连接测试成功')}>重新检测</button>{current.authType==='oauth'&&<button type="button" disabled={busy} onClick={()=>void run(()=>window.ailo.mcpAuthorize(current.id),'已重新授权并完成测试')}>重新授权</button>}<button type="button" disabled={busy||!current.enabled} onClick={()=>void run(()=>window.ailo.mcpDisconnect(current.id),'连接已断开，本机凭据已清除')}>断开连接</button></>}</div>
    </form>
    {busy&&selected&&draft.authType==='oauth'&&<button type="button" onClick={()=>void window.ailo.mcpDisconnect(selected).catch(e=>setError(String(e)))}>取消授权</button>}
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    {current&&<>{!!current.pendingCalls.length&&<details open><summary>待核对操作（{current.pendingCalls.length}）</summary><p className="extension-note">这些请求可能已执行。请先到服务端核对结果，再解除重复提交限制。</p>{current.pendingCalls.map(call=><div className="mcp-tool" key={call.id}><strong>{call.tool}</strong><p>{call.purpose} · {new Date(call.at).toLocaleString('zh-CN')}</p><pre>{JSON.stringify(call.params,null,2)}</pre><button type="button" disabled={busy} onClick={()=>{if(window.confirm('已在服务端核对此操作的结果？解除限制后，同样的参数可以再次提交。'))void run(()=>window.ailo.mcpResolveCall({id:current.id,callId:call.id}),'已解除此操作的重复提交限制');}}>已核对结果，解除限制</button></div>)}</details>}<details open className="mcp-tools"><summary>可用工具（{current.tools.length}）</summary>{!current.tools.length?<p>完成连接测试后显示工具。</p>:current.tools.map(tool=><div className="mcp-tool" key={tool.name}><strong>{tool.name}</strong><p>{tool.description||'服务未提供说明。'}</p><label>工具权限<select aria-label={'工具权限 '+tool.name} value={tool.permission} disabled={busy} onChange={e=>void run(()=>window.ailo.mcpPermissions({id:current.id,permissions:{[tool.name]:e.target.value as MCPPermission}}),'工具权限已更新')}><option value="ask">每次确认</option>{tool.readOnly&&<option value="read">允许自动读取</option>}<option value="disabled">禁用</option></select></label><details><summary>参数定义</summary><pre>{JSON.stringify(tool.inputSchema,null,2)}</pre></details></div>)}</details><p className="extension-note">“允许自动读取”依据服务的只读声明，请仅对你信任的工具开启。工具定义发生变化后会恢复为每次确认。</p><div className="extension-actions"><button type="button" className="primary" disabled={busy||!current.connected||!current.tools.some(t=>t.permission!=='disabled')} onClick={()=>{dialog.current?.close();onTry(`查看“${current.name}”的可用工具，并说明可以帮我做什么。`,{mcpId:current.id});}}>在对话中使用 ↗</button><button type="button" disabled={busy} onClick={()=>{if(window.confirm('移除此连接及本机凭据？已有对话仍保留。'))void run(async()=>{await window.ailo.mcpRemove(current.id);dialog.current?.close();setSelected(null);},'连接已移除');}}>移除连接</button></div></>}
   </article>
  </dialog>
 </section>;
}
