import React,{useEffect,useState} from 'react';
import type {ProjectMemoryData} from './types';
const statusName:Record<string,string>={completed:'已完成',blocked:'受阻',paused:'已暂停',running:'执行中',understanding:'理解需求中',waiting_permission:'等待授权',waiting:'等待补充',pending:'待处理',done:'已完成',in_progress:'进行中'};
export function ProjectMemory({id,onSelect}:{id:string;onSelect:(id:string)=>void}){
 const [data,setData]=useState<ProjectMemoryData>(),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const d=await window.ailo.projectMemory(id);setData(d);setNotes(d.notes);setError('');}catch(e){setError(String(e));}}
 useEffect(()=>{void load();},[id]);
 return <section className="project-memory"><h2>项目记忆</h2><p className="muted">任务记录自动汇总；项目补充用于纠正旧记录，新对话会参考这些背景。</p><label>项目补充与纠正<textarea value={notes} maxLength={12000} onChange={e=>setNotes(e.target.value)} rows={5} placeholder="记录当前目标、约束或已改变的决定…"/></label><button disabled={!data||busy} onClick={async()=>{if(!data)return;setBusy(true);try{await window.ailo.saveProjectMemory(id,{notes,revision:data.revision});await load();}catch(e){setError(String(e));}finally{setBusy(false);}}}>保存补充</button><button disabled={busy} onClick={()=>void load()}>刷新</button>{!!data?.hiddenTaskIds?.length&&<button disabled={busy} onClick={async()=>{if(!data)return;setBusy(true);try{await window.ailo.saveProjectMemory(id,{notes,revision:data.revision,hiddenTaskIds:[]});await load();}catch(e){setError(String(e));}finally{setBusy(false);}}}>恢复已移出的来源</button>}{error&&<p role="alert" className="error">{error}</p>}{data?.records.map(r=><details key={r.taskId}><summary>{r.title} · {statusName[r.status]||r.status}</summary><p>{r.goal}</p><strong>任务中的决定</strong><ul>{r.decisions.map((d,i)=><li key={i}>{typeof d==='string'?d:JSON.stringify(d)}</li>)}</ul><strong>步骤与状态</strong><ul>{r.steps.map((value,i)=>{const step=value as {title?:string;status:string};return <li key={i}>{step.title} · {statusName[step.status]||step.status}</li>;})}</ul><button onClick={()=>onSelect(r.taskId)}>查看来源对话</button><button disabled={busy||!data} onClick={async()=>{if(!data)return;setBusy(true);try{await window.ailo.saveProjectMemory(id,{notes,revision:data.revision,hiddenTaskIds:[...(data.hiddenTaskIds||[]),r.taskId]});await load();}catch(e){setError(String(e));}finally{setBusy(false);}}}>移出项目记忆</button></details>)}</section>;
}
