import React,{useEffect,useRef,useState} from 'react';
import type {Model,Schedule,ScheduleInput,Task} from './types';
import {AssistantText} from './assistant-text';
import {Icon} from './icon';
const dateLabel=(value:string)=>new Date(value).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const localDate=(value:number)=>{const d=new Date(value);return new Date(value-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const examples=[{title:'每日工作计划',prompt:'请为我制定今天的工作规划，提供三个优先事项、时间安排和一个复盘问题。',frequency:'daily' as const},{title:'每周学习安排',prompt:'请为我安排一周的 AI 学习计划，每天 30 分钟，包含学习主题和实践练习。',frequency:'weekly' as const},{title:'每周灵感清单',prompt:'请给我五个适合独立开发者的小产品创意，说明目标用户、核心价值和最小实现范围。',frequency:'weekly' as const},{title:'晚间复盘提醒',prompt:'提醒我做晚间复盘，并给出三个简短问题，帮助我回顾今天的收获和明天的重点。',frequency:'daily' as const}];
export function Schedules({initialId,focusHistory=false,tasks,models,defaultModelId,onOpen,onModels,onFeishu,onChanged}:{initialId?:string;focusHistory?:boolean;tasks:Task[];models:Model[];defaultModelId:string;onOpen:(id:string)=>Promise<void>;onModels:()=>void;onFeishu:()=>void;onChanged:()=>Promise<void>}){
 const [historyMode,setHistoryMode]=useState(focusHistory);
 const [liveTasks,setLiveTasks]=useState<Task[]|null>(null),[sessions,setSessions]=useState<Awaited<ReturnType<typeof window.ailo.sessions>>>([]),[now,setNow]=useState(Date.now());
 const [items,setItems]=useState<Schedule[]>([]),[selected,setSelected]=useState<string|undefined>(initialId),[draft,setDraft]=useState<ScheduleInput|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[loaded,setLoaded]=useState(false);
 async function refresh(){setItems(await window.ailo.schedulesList());setLoaded(true);}
 useEffect(()=>{let alive=true,inFlight=false;const poll=async()=>{if(inFlight)return;inFlight=true;try{const [list,state,live]=await Promise.all([window.ailo.schedulesList(),window.ailo.read(),window.ailo.sessions()]);if(alive){setItems(list);setLiveTasks(state.tasks);setSessions(live);setLoaded(true);}}catch(e){if(alive)setError((e as Error).message);}finally{inFlight=false;}};void poll();const timer=setInterval(()=>void poll(),3000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{alive=false;clearInterval(timer);clearInterval(clock);};},[]);
 const recordsFor=liveTasks||tasks;

 const historyRef=useRef<HTMLElement>(null),historyOpened=useRef(false);
 const current=items.find(i=>i.id===selected);
 function create(example?:typeof examples[number]){setError('');setDraft({title:example?.title||'',prompt:example?.prompt||'',frequency:example?.frequency||'daily',modelId:models.find(m=>m.id===defaultModelId)?.id||models[0]?.id||'',time:'09:00',weekday:1,at:localDate(Date.now()+3600000)});}
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await refresh();await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const records = current ? [...current.runs, ...recordsFor.filter(t=>t.scheduledTaskId===current.id&&!current.runs.some(r=>r.taskId===t.id)).map(t=>({id:t.scheduledRunId||t.id,taskId:t.id,at:t.scheduledAt||t.created,status:(t.lastError?'failed':t.messages?.at(-1)?.role==='assistant'?'completed':'failed') as 'failed'|'completed',error:t.lastError}))].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)) : [];
 const latest=records[0];
 const historyDates=[...new Set(records.slice(1).map(r=>new Date(r.at).toLocaleDateString('zh-CN')))];
 useEffect(()=>{if(focusHistory&&loaded&&current&&!historyOpened.current&&historyRef.current){historyOpened.current=true;historyRef.current.scrollIntoView({block:'start'});historyRef.current.querySelector<HTMLElement>('h3')?.focus({preventScroll:true});}},[focusHistory,loaded,current?.id,records.length]);
 function resultBody(run:Schedule['runs'][number]) {
   const record=recordsFor.find(t=>t.id===run.taskId);
   const reply=record?.messages?.filter(m=>m.role==='assistant').at(-1)?.content || record?.answer;
   const session=sessions.find(s=>s.taskId===run.taskId);
   const step=record?.agentRun?.steps.find(s=>s.status==='running')?.title;
   const update=[session?.updatedAt,record?.agentRun?.updatedAt].filter((t):t is string=>!!t).sort((a,b)=>Date.parse(b)-Date.parse(a))[0];
   const elapsed=Math.max(0,Math.floor((now-Date.parse(run.startedAt||run.at))/1000));
   const duration=elapsed<60?`${elapsed} 秒`:`${Math.floor(elapsed/60)} 分 ${elapsed%60} 秒`;
   const waiting=record?.agentRun?.contextUsage?.status==='sending';
   return <div className="schedule-result-body">{['running','queued'].includes(run.status)?<div className="schedule-live-progress" role="status"><strong>{run.status==='queued'?'等待空闲执行位置':step||'正在处理你的任务'}</strong>{run.status==='running'&&<p>{session?.status&&session.status!=='正在执行…'?session.status:waiting?'等待模型返回下一步…':record?.agentRun?.inFlight?.purpose||'正在准备下一步…'}</p>}<div><span>{run.status==='queued'?'已等待':'已执行'} {duration}</span><span>最近更新：{update?new Date(update).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'等待首次进展'}</span></div>{run.status==='running'&&update&&now-Date.parse(update)>120000&&<small>暂未收到新的进展，可能仍在等待模型，可打开记录查看。</small>}</div>:<>{run.error&&<p role="alert" className="error">{run.error}</p>}{reply?<div className="assistant-text"><AssistantText content={reply}/></div>:<p className="muted">{record?'暂无结果，请打开记录查看执行情况。':'执行记录暂不可用。'}</p>}</>}<button disabled={busy||!record} onClick={()=>void action(()=>onOpen(run.taskId))}>{['running','queued'].includes(run.status)?'查看执行进度 ↗':'打开记录，继续讨论 ↗'}</button></div>;
 }
 const running=current?.runs.some(r=>['running','queued'].includes(r.status));
 const scheduleLabel=(t:Schedule)=>t.frequency==='once'?'仅一次':t.frequency==='daily'?`每天 ${t.time}`:`每周${'日一二三四五六'[t.weekday!]} ${t.time}`;
 return <section className="schedules-page">
  <aside className="schedule-list"><button className="primary schedule-new" onClick={()=>create()}><Icon name="plus"/>新建任务</button><input aria-label="搜索定时任务" placeholder="搜索任务…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="muted">任务 · {items.length}</p>{items.filter(t=>t.title.includes(query)).map(t=><button className={'schedule-list-item '+(selected===t.id&&!draft?'selected':'')} key={t.id} onClick={()=>{setSelected(t.id);setHistoryMode(false);setDraft(null);setError('');}}><strong>{t.title}</strong><small>{t.runs.some(r=>['running','queued'].includes(r.status))?(t.runs.some(r=>r.status==='running')?'正在执行':'排队中'):!t.enabled?'已暂停 / 已结束':t.nextAt?dateLabel(t.nextAt):'尚未安排'}</small></button>)}{loaded&&!items.length&&<p className="muted">暂无已安排的任务</p>}</aside>
  <div className="schedule-content"><p className="schedule-notice">本机定时执行 · Ailo 运行且电脑唤醒时自动处理。错过的任务恢复后补跑一次。时间随本机时区（{Intl.DateTimeFormat().resolvedOptions().timeZone}）。</p>{error&&<p className="error" role="alert">{error}</p>}
  {draft?<form className="schedule-form" onSubmit={e=>{e.preventDefault();void action(async()=>{const saved=await window.ailo.schedulesSave({...draft,at:draft.frequency==='once'?new Date(draft.at!).toISOString():undefined});setSelected(saved.id);setDraft(null);});}}>
    <h2>{draft.id?'编辑任务':'新建定时任务'}</h2><label>任务名称<input required maxLength={80} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="例如：每周学习安排"/></label>
    <label>希望 Ailo 做什么<textarea required maxLength={20000} rows={5} value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})} placeholder="说明任务内容、输出格式和需要关注的重点…"/></label>
    <div className="schedule-fields"><label>重复周期<select value={draft.frequency} onChange={e=>setDraft({...draft,frequency:e.target.value as ScheduleInput['frequency']})}><option value="once">仅一次</option><option value="daily">每天</option><option value="weekly">每周</option></select></label>
    {draft.frequency==='weekly'&&<label>星期<select value={draft.weekday} onChange={e=>setDraft({...draft,weekday:Number(e.target.value)})}>{[1,2,3,4,5,6,0].map(d=><option value={d} key={d}>星期{'日一二三四五六'[d]}</option>)}</select></label>}
    <label>执行时间{draft.frequency==='once'?<input type="datetime-local" required value={draft.at?.slice(0,16)} onChange={e=>setDraft({...draft,at:e.target.value})}/>:<input type="time" required value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/>}</label></div>
    <label>使用模型<select required value={draft.modelId} onChange={e=>setDraft({...draft,modelId:e.target.value})}><option value="" disabled>选择模型</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{!models.length&&<button type="button" onClick={onModels}>先配置模型</button>}
    <label className="schedule-checkbox"><input type="checkbox" checked={!!draft.searchEnabled} onChange={e=>setDraft({...draft,searchEnabled:e.target.checked})}/>允许联网搜索（需先在扩展中配置）</label>
    <div className="schedule-connection-option"><label className="schedule-checkbox"><input type="checkbox" checked={!!draft.feishuEnabled} onChange={e=>setDraft({...draft,feishuEnabled:e.target.checked})}/>允许连接飞书</label><button type="button" onClick={onFeishu}>配置飞书 ↗</button></div><p className="muted">每次执行使用所选模型，会产生模型服务用量。结果按执行时间保存在当前任务中。启用飞书后使用已连接的账号与权限；需要人工确认的操作仍需你处理。</p>
    <div className="schedule-actions"><button className="primary" disabled={busy||!models.length}>保存任务</button><button type="button" disabled={busy} onClick={()=>setDraft(null)}>取消</button></div>
  </form>:current?<article className={"schedule-detail"+(historyMode?" schedule-history-focus":"")}><div className="schedule-symbol"><Icon name="clock"/></div><h2>{current.title}</h2>{historyMode&&<button className="schedule-detail-link" onClick={()=>setHistoryMode(false)}>查看任务详情 ↗</button>}<div className="schedule-configuration"><p className="muted">{scheduleLabel(current)} · {models.find(m=>m.id===current.modelId)?.name||'模型已移除'}{!current.enabled?' · 已暂停 / 已结束':''}</p><p className="schedule-prompt">{current.prompt}</p>{(current.searchEnabled||current.feishuEnabled)&&<p className="muted">已启用：{[current.searchEnabled&&"联网搜索",current.feishuEnabled&&"飞书"].filter(Boolean).join(" · ")}</p>}<p>下次执行：{current.enabled&&current.nextAt?dateLabel(current.nextAt):'未安排'}</p><div className="schedule-actions"><button className="primary" disabled={busy||running} onClick={()=>void action(()=>window.ailo.schedulesRun(current.id))}>{running?(current.runs.some(r=>r.status==='running')?'正在执行…':'排队中…'):'立即执行'}</button><button disabled={busy||running} onClick={()=>setDraft({...current,at:current.at?localDate(Date.parse(current.at)):localDate(Date.now()+3600000)})}>编辑</button><button title="仅调整后续定时安排，不停止当前执行" disabled={busy} onClick={()=>void action(()=>window.ailo.schedulesToggle({id:current.id,enabled:!current.enabled}))}>{current.enabled?'暂停安排':'启用安排'}</button><button disabled={busy||running} onClick={()=>{if(confirm('删除这个定时任务？已生成的对话会保留。'))void action(async()=>{await window.ailo.schedulesRemove(current.id);setSelected(undefined);});}}>删除</button></div>
    </div>
    <section className="schedule-latest"><div className="schedule-result-heading"><h3>最新结果</h3>{latest&&<span>{dateLabel(latest.at)} · {latest.status==='queued'?'排队中':latest.status==='running'?'正在执行':latest.status==='completed'?'已完成':'未完成'}</span>}</div>{latest?resultBody(latest):<p className="muted">执行后，结果会显示在这里。</p>}</section>
    <section ref={historyRef} className="schedule-history"><h3 tabIndex={-1}>历史记录 <small>{records.length-1}</small></h3>{records.length<2&&<p className="muted">暂无更早的执行记录。</p>}{historyDates.map(date=>{const Container=historyMode?"div":"details";const Heading=historyMode?"div":"summary";return <Container key={current.id+date} className="schedule-history-day"><Heading className="schedule-history-date">{date}<span>{records.slice(1).filter(r=>new Date(r.at).toLocaleDateString('zh-CN')===date).length} 次执行</span></Heading>{records.slice(1).filter(r=>new Date(r.at).toLocaleDateString('zh-CN')===date).map(run=><div className="schedule-history-result" key={run.id}><div className="schedule-result-heading"><span>{new Date(run.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} · {run.status==='completed'?'已完成':run.status==='queued'?'排队中':run.status==='running'?'正在执行':'未完成'}</span></div>{resultBody(run)}</div>)}</Container>;})}</section>

  </article>:<div className="schedule-empty"><div className="schedule-symbol"><Icon name="clock"/></div><h2>把重复的事，交给 Ailo</h2><p className="muted">安排一个时间，让 Ailo 按时生成计划、整理思路或提醒你复盘。</p><div className="schedule-examples">{examples.map(example=><button key={example.title} onClick={()=>create(example)}><Icon name="sparkles"/><span><strong>{example.title}</strong><small>{example.prompt}</small></span></button>)}</div></div>}
  </div>
 </section>;
}
