const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {createAMap}=require('../apps/desktop/amap-mcp.cjs');
const key='test-key-123456';const tool={name:'maps_weather',description:'天气',inputSchema:{type:'object',properties:{city:{type:'string'}},required:['city']}};
async function setup(t,fetchImpl,extra={}){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-amap-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));const amap=createAMap({directory,safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from('encrypted:'+s),decryptString:b=>b.toString().slice(10)},fetchImpl,...extra});await amap.save({key});return {amap,directory};}
function mock(calls,{sse=false,tools=[tool],error=false}={}){return async(url,options)=>{assert.equal(new URL(url).origin,'https://mcp.amap.com');assert.equal(new URL(url).searchParams.get('key'),key);assert.equal(options.redirect,'error');const request=JSON.parse(options.body);calls.push(request);if(request.method==='notifications/initialized')return new Response(null,{status:202});if(request.method!=='initialize')assert.equal(options.headers['Mcp-Session-Id'],'session');const result=request.method==='initialize'?{protocolVersion:'2025-03-26',capabilities:{tools:{}}}:request.method==='tools/list'?{tools}:{content:[{type:'text',text:'晴天 '+key}],isError:error};const obj={jsonrpc:'2.0',id:request.id,result};return new Response(sse?'event: message\r\ndata: '+JSON.stringify(obj)+'\r\n\r\n':JSON.stringify(obj),{headers:{'content-type':sse?'text/event-stream':'application/json','mcp-session-id':'session'}});};}
test('initializes, discovers and calls official server with session headers; key never enters results/status',async t=>{const calls=[];const {amap}=await setup(t,mock(calls));const status=await amap.test();assert.equal(status.connected,true);assert.deepEqual(status.tools,['maps_weather']);assert.ok(!JSON.stringify(status).includes(key));const result=await amap.execute({operation:'call',query:'maps_weather',params:{city:'北京'}},new AbortController().signal);assert.match(result.text,/晴天/);assert.ok(!result.text.includes(key));assert.equal(calls.at(-1).method,'tools/call');assert.deepEqual(calls.at(-1).params.arguments,{city:'北京'});});
test('handles SSE responses and preserves tool isError',async t=>{const {amap}=await setup(t,mock([],{sse:true,error:true}));const result=await amap.execute({operation:'call',query:'maps_weather',params:{city:'北京'}});assert.equal(result.isError,true);});
test('requires confirmation for unknown side effects and cancellation never calls tool',async t=>{const calls=[];const {amap}=await setup(t,mock(calls,{tools:[{...tool,name:'personal_map'}]}));await assert.rejects(amap.execute({operation:'call',query:'personal_map',params:{}}),{code:'AMAP_DECLINED'});assert.ok(!calls.some(c=>c.method==='tools/call'));});
test('confirmed non-read tool executes and unknown tool is refused',async t=>{const calls=[];const {amap}=await setup(t,mock(calls,{tools:[{...tool,name:'personal_map'}]}),{confirmWrite:async()=>true});await amap.execute({operation:'call',query:'personal_map',params:{}});assert.equal(calls.at(-1).method,'tools/call');await assert.rejects(amap.execute({operation:'call',query:'missing',params:{}}),/列表/);});
test('errors redact provider data and failed verification clears connection status',async t=>{let reject=false;const success=mock([]);const {amap}=await setup(t,(...args)=>reject?new Response('private '+key,{status:403}):success(...args));await amap.test();reject=true;await assert.rejects(amap.test(),e=>!e.message.includes(key)&&e.code==='AMAP_UNAVAILABLE');assert.equal((await amap.status()).connected,false);});
test('saving blank key preserves credentials, disconnect removes config and blocks future execution',async t=>{const {amap,directory}=await setup(t,mock([]));await amap.save({key:''});await amap.test();const status=await amap.disconnect();assert.equal(status.configured,false);await assert.rejects(fs.access(path.join(directory,'amap-mcp.json')));await assert.rejects(amap.execute({operation:'list'}),/配置/);});
test('malformed responses, unknown operations and array parameters are rejected',async t=>{const {amap}=await setup(t,async()=>new Response('bad'));await assert.rejects(amap.test(),{code:'AMAP_UNAVAILABLE'});assert.throws(()=>amap.execute({operation:'bad'}));assert.throws(()=>amap.execute({operation:'call',query:'maps_weather',params:[]}));});
test('Agent chat invokes AMap list and call, returning real tool output without local artifacts',async t=>{const {amap,directory}=await setup(t,mock([]));const actions=[{action:'route',kind:'chat'},{action:'amap',operation:'list'},{action:'amap',operation:'call',query:'maps_weather',params:{city:'北京'}},{action:'reply',text:'北京晴天'}];const {runAgent}=require('../apps/desktop/agent/runner.cjs');const result=await runAgent({base:path.join(directory,'agent'),task:{id:'t',request:'北京天气'},model:{contextWindow:32768},signal:new AbortController().signal,amap,ask:async()=>({content:JSON.stringify(actions.shift())})});assert.equal(result.content,'北京晴天');assert.equal(result.agentRun.artifacts.length,0);});
