const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const ExcelJS=require('../apps/desktop/node_modules/exceljs');
const {parseDocument}=require('../apps/desktop/document-parser.cjs');
const {previewFile,editFile}=require('../apps/desktop/artifact-edit.cjs');
const {readMemory,saveMemory}=require('../apps/desktop/project-memory.cjs');
const {workspacePath}=require('../apps/desktop/agent/workspace-path.cjs');
const {key,writeJson}=require('../apps/desktop/agent/workspace.cjs');
function pdf(text){const stream=text?`BT /F1 12 Tf 72 720 Td (${text}) Tj ET`:'';const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let content='%PDF-1.4\n';const offsets=[0];objs.forEach((o,i)=>{offsets.push(Buffer.byteLength(content));content+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=Buffer.byteLength(content);content+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(x=>`${String(x).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return content;}
test('PDF retains page locations and identifies pages needing OCR',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-doc-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'test.pdf');await fs.writeFile(file,pdf('Quarterly report'));const p=await parseDocument(file);assert.match(p.text,/第 1 页/);assert.match(p.text,/Quarterly report/);assert.equal(p.status,'parsed');await fs.writeFile(file,pdf(''));assert.equal((await parseDocument(file)).status,'needs_ocr');});
test('XLSX retains formulas, locates cells, edits and restores actual workbook',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-sheet-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('销售');sheet.getCell('A1').value=12;sheet.getCell('B1').value={formula:'A1*2',result:24};const file=path.join(dir,'sales.xlsx');await book.xlsx.writeFile(file);const p=await parseDocument(file);assert.match(p.text,/销售/);assert.match(p.text,/B1: 公式=A1\*2；缓存值=24/);const v=await previewFile(file);assert.equal(v.kind,'spreadsheet');const edited=await editFile(dir,path.join(dir,'backups'),'sales.xlsx',{version:v.version,sheet:'销售',address:'A1',text:'新的值'});assert.equal(edited.sheets[0].cells[0].text,'新的值');await assert.rejects(editFile(dir,path.join(dir,'backups'),'sales.xlsx',{version:v.version,text:'stale'}),/已变化/);const restored=await editFile(dir,path.join(dir,'backups'),'sales.xlsx',{version:edited.version,operation:'restore'});assert.equal(restored.sheets[0].cells[0].text,'12');});
test('text editing rejects stale versions and unsafe paths',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-edit-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.writeFile(path.join(dir,'report.md'),'# Draft');const v=await previewFile(path.join(dir,'report.md'));assert.equal(v.kind,'markdown');const updated=await editFile(dir,path.join(dir,'backups'),'report.md',{version:v.version,text:'# Final'});assert.equal(updated.content,'# Final');await assert.rejects(editFile(dir,path.join(dir,'backups'),'../outside',{version:v.version,text:'bad'}),/相对路径/);});
test('project memory has evidence, correction version conflicts, and isolation',async t=>{const base=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-memory-'));t.after(()=>fs.rm(base,{recursive:true,force:true}));const task={id:'task-a',projectId:'p1',title:'报告'};await writeJson(path.join(workspacePath(base,task),'runs',key(task.id)+'.json'),{goal:'生成报告',status:'blocked',decisions:['需要来源'],steps:[{title:'导出',status:'pending'}]});const first=await readMemory(base,{id:'p1'},[task]);assert.equal(first.records[0].status,'blocked');assert.equal(first.records[0].steps[0].status,'pending');await saveMemory(base,'p1',{revision:0,notes:'改为仅输出 Markdown'});await assert.rejects(saveMemory(base,'p1',{revision:0,notes:'old'}),/已更新/);assert.equal((await readMemory(base,{id:'p2'},[task])).records.length,0);assert.equal((await readMemory(base,{id:'p1'},[task])).notes,'改为仅输出 Markdown');});
test('new conversations receive project evidence and corrections; hidden sources stay out',async t=>{const base=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-memory-agent-'));t.after(()=>fs.rm(base,{recursive:true,force:true}));const old={id:'earlier',projectId:'shared'};await writeJson(path.join(workspacePath(base,old),'runs',key(old.id)+'.json'),{taskId:old.id,goal:'旧任务',status:'blocked',steps:[],decisions:['旧决定']});await saveMemory(base,'shared',{revision:0,notes:'新决定：仅输出文字'});const {runAgent}=require('../apps/desktop/agent/runner.cjs');let seen;await runAgent({base,task:{id:'new-chat',projectId:'shared',request:'项目进展',materials:[]},model:{},signal:new AbortController().signal,ask:async messages=>{seen=JSON.parse(messages.at(-1).content);return {content:JSON.stringify(seen.phase==='route'?{action:'route',kind:'chat'}:{action:'reply',text:'已参考项目背景'})};}});assert.equal(seen.projectMemory.records[0].status,'blocked');assert.equal(seen.projectMemory.notes,'新决定：仅输出文字');await saveMemory(base,'shared',{revision:1,notes:'新决定：仅输出文字',hiddenTaskIds:['earlier']});assert.equal((await readMemory(base,{id:'shared'},[old])).records.length,0);});
test('Agent writes keep an out-of-workspace backup usable by the viewer',async t=>{const base=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-agent-backup-'));t.after(()=>fs.rm(base,{recursive:true,force:true}));const workspace=await require('../apps/desktop/agent/workspace.cjs').createWorkspace(base,{id:'backup-task',materials:[]});const {execute}=require('../apps/desktop/agent/tools.cjs');const signal=new AbortController().signal;await execute(workspace,{action:'write_file',path:'report.md',content:'旧报告'},signal);await execute(workspace,{action:'write_file',path:'report.md',content:'新报告'},signal);const v=await previewFile(path.join(workspace.files,'report.md'));const restored=await editFile(workspace.files,path.join(workspace.project,'backups'),'report.md',{version:v.version,operation:'restore'});assert.equal(restored.content,'旧报告');});
test('native spreadsheet edit preserves types and rejects stale versions; chat cannot edit',async t=>{const base=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-sheet-tool-'));t.after(()=>fs.rm(base,{recursive:true,force:true}));const workspace=await require('../apps/desktop/agent/workspace.cjs').createWorkspace(base,{id:'sheet-task',materials:[]});const book=new ExcelJS.Workbook();const sheet=book.addWorksheet('数据');sheet.getCell('A1').value=1;sheet.getCell('B1').value='保留';await book.xlsx.writeFile(path.join(workspace.files,'table.xlsx'));const {execute}=require('../apps/desktop/agent/tools.cjs'),signal=new AbortController().signal;const source=await execute(workspace,{action:'read_file',path:'table.xlsx'},signal);const action={action:'edit_spreadsheet',path:'table.xlsx',data:{version:source.sha256,sheet:'数据',cells:[{address:'A1',value:42},{address:'C1',value:true}]}};await execute(workspace,action,signal);await assert.rejects(execute(workspace,action,signal),/已变化/);const updated=new ExcelJS.Workbook();await updated.xlsx.readFile(path.join(workspace.files,'table.xlsx'));assert.equal(updated.getWorksheet('数据').getCell('A1').value,42);assert.equal(updated.getWorksheet('数据').getCell('C1').value,true);assert.equal(updated.getWorksheet('数据').getCell('B1').value,'保留');assert.ok(!require('../apps/desktop/agent/protocol.cjs').allowedActions({phase:'chat'}).includes('edit_spreadsheet'));});
