const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createKnowledge}=require('../apps/desktop/knowledge.cjs');
async function setup(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-kb-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return {dir,kb:createKnowledge(dir)};}
async function doc(dir,name,text){const file=path.join(dir,name);await fs.writeFile(file,text);return file;}
test('creates, edits, imports full text beyond attachment truncation and persists across restart',async t=>{const {dir,kb}=await setup(t);const lib=await kb.save({name:'工作规范',description:'团队规则'});const file=await doc(dir,'policy.md','背景'.repeat(60000)+'请假需要提前三天申请。');assert.equal((await kb.import(lib.id,[file]))[0].status,'imported');const restored=createKnowledge(dir);const list=await restored.list();assert.equal(list[0].documents.length,1);assert.ok(list[0].documents[0].chars>100000);assert.ok(!JSON.stringify(list).includes('提前三天'));const result=await restored.search({libraryIds:[lib.id],query:'请假'});assert.equal(result.hits.length,1);assert.match(result.hits[0].text,/提前三天/);assert.match(result.hits[0].citation,/policy.md/);await restored.save({id:lib.id,name:'新名称',description:'更新'});assert.equal((await restored.list())[0].documents.length,1);});
test('deduplicates content, isolates selected libraries and rejects traversal or cross-library reads',async t=>{const {dir,kb}=await setup(t);const a=await kb.save({name:'A'}),b=await kb.save({name:'B'});const file=await doc(dir,'secret.txt','机密定价为十万元');await kb.import(b.id,[file]);assert.equal((await kb.import(b.id,[file]))[0].status,'duplicate');assert.deepEqual((await kb.scope([a.id]).execute({operation:'search',query:'定价'})).hits,[]);const d=(await kb.list()).find(l=>l.id===b.id).documents[0];await assert.rejects(kb.scope([a.id]).execute({operation:'read',id:b.id,entry:d.id}),/未选择/);await assert.rejects(kb.read({libraryId:'../../outside',documentId:d.id}));});
test('returns per-file failures, rejects unsupported formats and retains successful imports',async t=>{const {dir,kb}=await setup(t);const lib=await kb.save({name:'测试'});const pdf=await doc(dir,'bad.pdf','fake'),empty=await doc(dir,'empty.md',''),ok=await doc(dir,'ok.txt','正常正文');const result=await kb.import(lib.id,[pdf,empty,ok]);assert.deepEqual(result.map(r=>r.status),['failed','failed','imported']);assert.equal((await kb.list())[0].documents.length,1);});
test('pagination reconstructs text and deletion immediately removes search/read access without touching source',async t=>{const {dir,kb}=await setup(t);const lib=await kb.save({name:'库'});const text='流程指南'.repeat(3500),source=await doc(dir,'long.md',text);await kb.import(lib.id,[source]);const d=(await kb.list())[0].documents[0];let offset=0,result='';do{const p=await kb.read({libraryId:lib.id,documentId:d.id,offset});result+=p.text;if(p.next===null)break;offset=p.next;}while(true);assert.equal(result,text);await kb.removeDocument({libraryId:lib.id,documentId:d.id});assert.deepEqual((await kb.search({libraryIds:[lib.id],query:'指南'})).hits,[]);await assert.rejects(kb.read({libraryId:lib.id,documentId:d.id}),/删除/);assert.equal(await fs.readFile(source,'utf8'),text);await kb.remove(lib.id);assert.deepEqual(await kb.list(),[]);});
test('index handles prototype-like tokens and bounded Chinese/English search',async t=>{const {dir,kb}=await setup(t);const lib=await kb.save({name:'代码规范'});await kb.import(lib.id,[await doc(dir,'code.md','constructor __proto__ API 使用说明')]);assert.ok((await kb.search({libraryIds:[lib.id],query:'constructor'})).hits.length);assert.equal((await kb.search({libraryIds:[lib.id],query:'完全无关'})).hits.length,0);});
test('Agent receives only selected library metadata, retrieves sources and replies without local artifacts',async t=>{const {dir,kb}=await setup(t);const lib=await kb.save({name:'人事规范'});await kb.import(lib.id,[await doc(dir,'leave.md','请假需要提前三天申请。')]);const {runAgent}=require('../apps/desktop/agent/runner.cjs');let n=0;const actions=[{action:'route',kind:'chat'},{action:'knowledge',operation:'search',query:'请假'},{action:'reply',text:'请假需要提前三天申请。[知识库：人事规范 / leave.md，片段 1]'}];const result=await runAgent({base:path.join(dir,'agent'),task:{id:'t',request:'请假需要提前多久'},model:{contextWindow:32768},signal:new AbortController().signal,knowledge:kb.scope([lib.id]),ask:async messages=>{const state=JSON.parse(messages.at(-1).content);assert.equal(state.knowledgeLibraries[0].name,'人事规范');if(n===2)assert.match(state.toolResults.at(-1).result.hits[0].text,/提前三天/);n++;return {content:JSON.stringify(actions.shift())};}});assert.match(result.content,/leave.md/);assert.equal(result.agentRun.artifacts.length,0);});
