const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHash}=require('node:crypto');
const {authorize,refresh,discover}=require('../apps/desktop/mcp-oauth.cjs');
const {createMCPConnections}=require('../apps/desktop/mcp-connections.cjs');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const signal=()=>new AbortController().signal;
function authFetch(calls,{pkce=true,resource='https://notes.example/mcp',registration=true,tokenError=false}={}){return async(url,options)=>{calls.push({url,options});if(url.includes('oauth-protected-resource'))return Response.json({resource,authorization_servers:['https://login.example'],scopes_supported:['notes:read']});if(url.includes('oauth-authorization-server'))return Response.json({issuer:'https://login.example',authorization_endpoint:'https://login.example/authorize',token_endpoint:'https://login.example/token',...(registration?{registration_endpoint:'https://login.example/register'}:{}),code_challenge_methods_supported:pkce?['S256']:[]});if(url.endsWith('/register'))return Response.json({client_id:'ailo-public',token_endpoint_auth_method:'none'});if(url.endsWith('/token'))return tokenError?new Response('secret',{status:400}):Response.json({access_token:'access-private',refresh_token:'refresh-private',token_type:'Bearer',expires_in:3600});throw Error('unexpected endpoint');};}
test('OAuth discovery binds the resource and uses PKCE, state, resource indicators and public registration',async()=>{const calls=[];let authUrl;const value=await authorize({url:'https://notes.example/mcp',fetchImpl:authFetch(calls),signal:signal(),receiveCallback:async({state,onReady})=>{authUrl=new URL(await onReady('http://127.0.0.1:12345/callback'));assert.equal(authUrl.searchParams.get('state'),state);assert.ok(state.length>30);return {code:'auth-code',redirectUri:'http://127.0.0.1:12345/callback'};}});assert.equal(value.accessToken,'access-private');assert.equal(value.resource,'https://notes.example/mcp');const body=new URLSearchParams(calls.find(c=>c.url.endsWith('/token')).options.body);assert.equal(body.get('code'),'auth-code');assert.equal(body.get('resource'),value.resource);assert.equal(createHash('sha256').update(body.get('code_verifier')).digest('base64url'),authUrl.searchParams.get('code_challenge'));assert.equal(body.get('client_id'),'ailo-public');assert.equal(authUrl.searchParams.get('code_challenge_method'),'S256');});
test('static public Client ID skips dynamic registration',async()=>{const calls=[];await authorize({url:'https://notes.example/mcp',clientId:'provided-id',fetchImpl:authFetch(calls,{registration:false}),signal:signal(),receiveCallback:async({onReady})=>{assert.equal(new URL(await onReady('http://127.0.0.1:1/callback')).searchParams.get('client_id'),'provided-id');return {code:'code',redirectUri:'http://127.0.0.1:1/callback'};}});assert.ok(!calls.some(c=>c.url.endsWith('/register')));});
test('wrong resource and absent PKCE are rejected before opening the browser',async()=>{for(const extra of [{resource:'https://other.example/mcp'},{pkce:false}])await assert.rejects(discover({url:'https://notes.example/mcp',fetchImpl:authFetch([],extra),signal:signal()}),{code:'MCP_AUTH_REQUIRED'});});
test('refresh preserves resource and rotated credentials, while errors reveal no provider body',async()=>{const credentials={clientId:'id',accessToken:'old',refreshToken:'old-refresh',resource:'https://notes.example/mcp',tokenEndpoint:'https://login.example/token'};const calls=[];const value=await refresh({credentials,fetchImpl:authFetch(calls),signal:signal()});assert.equal(value.refreshToken,'refresh-private');const body=new URLSearchParams(calls[0].options.body);assert.equal(body.get('grant_type'),'refresh_token');assert.equal(body.get('resource'),credentials.resource);await assert.rejects(refresh({credentials,fetchImpl:authFetch([],{tokenError:true}),signal:signal()}),e=>e.code==='MCP_AUTH_REQUIRED'&&!e.message.includes('secret'));});
test('OAuth manager encrypts tokens, refreshes before expiry and disconnect clears authorization',async t=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-oauth-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));let refreshed=0;const calls=[];const manager=createMCPConnections({directory,safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).map(n=>n^19),decryptString:b=>Buffer.from(b.map(n=>n^19)).toString()},openExternal:async()=>{},oauth:{authorize:async()=>({accessToken:'access-private',refreshToken:'refresh-private',expiresAt:Date.now()-1000,clientId:'id',resource:'https://notes.example/mcp',tokenEndpoint:'https://login.example/token'}),refresh:async({credentials})=>{refreshed++;return {...credentials,accessToken:'fresh-private',expiresAt:Date.now()+3600000};}},fetchImpl:async(url,options)=>{const r=JSON.parse(options.body);calls.push({r,headers:options.headers});if(r.method==='notifications/initialized')return new Response(null,{status:202});return Response.json({jsonrpc:'2.0',id:r.id,result:r.method==='initialize'?{protocolVersion:'2025-03-26'}:{tools:[]}});}});const s=await manager.save({name:'OAuth 笔记',description:'',url:'https://notes.example/mcp',authType:'oauth'});const verified=await manager.authorize(s.id);assert.equal(verified.connected,true);assert.equal(refreshed,1);assert.ok(calls.some(c=>c.headers.Authorization==='Bearer fresh-private'));assert.ok(!(await fs.readFile(path.join(directory,'mcp-connections.json'),'utf8')).includes('private'));const d=await manager.disconnect(s.id);assert.equal(d.hasCredential,false);await assert.rejects(manager.test(s.id),{code:'MCP_AUTH_REQUIRED'});});
