const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createMCPConnections}=require('../apps/desktop/mcp-connections.cjs');
const {allowedActions,actionTools}=require('../apps/desktop/agent/protocol.cjs');
const tool={name:'search_notes',description:'查找笔记',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query']},annotations:{readOnlyHint:true}};
const key='private-token-secret';
const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).map(b=>b^73),decryptString:b=>Buffer.from(b.map(n=>n^73)).toString()};
async function setup(t,options={}){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-mcp-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));const calls=[];const manager=createMCPConnections({directory,safeStorage,fetchImpl:mock(calls),...options});t.after(()=>manager.dispose());const server=await manager.save({name:'笔记服务',description:'笔记搜索',url:'https://notes.example/mcp',authType:'token',token:key});return {manager,server,calls,directory};}
function mock(calls,{tools=[tool],sse=false,toolResult={content:[{type:'text',text:'真实笔记 '+key}]} }={}){return async(url,options)=>{const req=JSON.parse(options.body);calls.push({req,url,headers:options.headers});assert.equal(options.redirect,'error');if(req.method==='notifications/initialized')return new Response(null,{status:202});if(req.method!=='initialize')assert.equal(options.headers['Mcp-Session-Id'],'session');const result=req.method==='initialize'?{protocolVersion:'2025-03-26',capabilities:{tools:{}}}:req.method==='tools/list'?{tools}:toolResult;return new Response(sse?'event: message\r\ndata: '+JSON.stringify({jsonrpc:'2.0',method:'notifications/progress',params:{progress:1}})+'\r\n\r\ndata: '+JSON.stringify({jsonrpc:'2.0',id:req.id,result})+'\r\n\r\n':JSON.stringify({jsonrpc:'2.0',id:req.id,result}),{headers:{'content-type':sse?'text/event-stream':'application/json','mcp-session-id':'session'}});};}
const call=id=>({operation:'call',id,query:'search_notes',params:{query:'需求'},purpose:'查询笔记'});
test('encrypted configuration, initialization and tools are usable without exposing credentials',async t=>{
 const {manager,server,calls,directory}=await setup(t);const verified=await manager.test(server.id);assert.equal(verified.connected,true);assert.equal(verified.tools[0].permission,'ask');assert.ok(!JSON.stringify(verified).includes(key));assert.ok(!(await fs.readFile(path.join(directory,'mcp-connections.json'),'utf8')).includes(key));
 const list=await manager.scope([server.id]).execute({operation:'list',id:server.id});assert.equal(list.tools[0].name,'search_notes');assert.equal(calls[0].headers.Authorization,'Bearer '+key);
});
test('default confirmation refusal never submits a tool and does not invalidate a working connection',async t=>{const {manager,server,calls}=await setup(t);await manager.test(server.id);await assert.rejects(manager.scope([server.id]).execute(call(server.id)),{code:'MCP_DECLINED'});assert.ok(!calls.some(c=>c.req.method==='tools/call'));assert.equal((await manager.list())[0].connected,true);});
test('selected read permission calls real tools, redacts outputs, and supports SSE and isError',async t=>{const calls=[];const {manager,server}=await setup(t,{fetchImpl:mock(calls,{sse:true,toolResult:{content:[{type:'text',text:key}],isError:true}})});await manager.test(server.id);await manager.permissions({id:server.id,permissions:{search_notes:'read'}});const result=await manager.scope([server.id]).execute(call(server.id));assert.equal(result.isError,true);assert.ok(!result.text.includes(key));assert.deepEqual(calls.at(-1).req.params.arguments,{query:'需求'});});
test('unselected connections, disabled tools and fabricated tools are rejected before invocation',async t=>{const {manager,server,calls}=await setup(t);await manager.test(server.id);await assert.rejects(manager.scope([]).execute(call(server.id)),/未在当前对话/);await manager.permissions({id:server.id,permissions:{search_notes:'disabled'}});await assert.rejects(manager.scope([server.id]).execute(call(server.id)),/禁用/);await assert.rejects(manager.scope([server.id]).execute({...call(server.id),query:'made_up'}),/不存在/);assert.ok(!calls.some(c=>c.req.method==='tools/call'));});
test('tool definition changes reset previously granted automatic permission',async t=>{let changed=false,confirmations=0;const calls=[];const {manager,server}=await setup(t,{fetchImpl:(...args)=>mock(calls,{tools:[{...tool,description:changed?'changed':'查找笔记'}]})(...args),confirmCall:async()=>{confirmations++;return true;}});await manager.test(server.id);await manager.permissions({id:server.id,permissions:{search_notes:'read'}});changed=true;await manager.scope([server.id]).execute(call(server.id));assert.equal(confirmations,1);assert.equal((await manager.list())[0].tools[0].permission,'ask');});
test('non-read tools cannot receive read permission and confirmed writes run exactly once',async t=>{const calls=[];const {manager,server}=await setup(t,{fetchImpl:mock(calls,{tools:[{...tool,annotations:{readOnlyHint:false}}]}),confirmCall:async()=>true});await manager.test(server.id);await assert.rejects(manager.permissions({id:server.id,permissions:{search_notes:'read'}}),/只读/);await manager.scope([server.id]).execute(call(server.id));assert.equal(calls.filter(c=>c.req.method==='tools/call').length,1);});
test('uncertain tool results are blocked and never replayed by the runtime',async t=>{const calls=[];const happy=mock(calls);const {manager,server,directory}=await setup(t,{fetchImpl:async(url,options)=>{if(JSON.parse(options.body).method==='tools/call'){calls.push({req:JSON.parse(options.body)});throw Error('socket disconnected '+key);}return happy(url,options);},confirmCall:async()=>true});await manager.test(server.id);const actions=[{action:'route',kind:'chat'},{action:'mcp',...call(server.id)}];const {runAgent}=require('../apps/desktop/agent/runner.cjs');const result=await runAgent({base:path.join(directory,'agent'),task:{id:'t',request:'读取笔记'},model:{contextWindow:32768},signal:new AbortController().signal,mcp:manager.scope([server.id]),ask:async()=>({content:JSON.stringify(actions.shift())})});assert.equal(result.agentRun.status,'blocked');assert.match(result.content,/先核对远端状态/);assert.equal(calls.filter(c=>c.req.method==='tools/call').length,1);assert.ok(!result.content.includes(key));});
test('disconnect removes secrets and prevents use; reconnect requires credentials',async t=>{const {manager,server}=await setup(t);await manager.test(server.id);const disconnected=await manager.disconnect(server.id);assert.equal(disconnected.hasCredential,false);assert.equal(disconnected.connected,false);await assert.rejects(manager.scope([server.id]).execute(call(server.id)),/断开/);await assert.rejects(manager.save({id:server.id,name:server.name,description:'',url:server.url,authType:'token',token:''}),/Token/);await manager.remove(server.id);assert.deepEqual(await manager.list(),[]);});
test('blank token preserves only the same service, auth type and header',async t=>{const {manager,server}=await setup(t);const input={id:server.id,name:server.name,description:'',url:server.url,authType:'token',token:''};assert.equal((await manager.save(input)).hasCredential,true);await assert.rejects(manager.save({...input,url:'https://other.example/mcp'}),/Token/);await assert.rejects(manager.save({...input,headerName:'X-API-Key'}),/Token/);});
test('URLs, headers, encryption and scope values are validated',async t=>{const {manager}=await setup(t);const base={name:'测试',description:'',url:'https://example.com/mcp',authType:'none'};for(const url of ['file:///tmp/a','http://remote.example/mcp','https://name:pass@example.com/mcp','https://example.com/mcp?key=secret'])await assert.rejects(manager.save({...base,url}));await assert.rejects(manager.save({...base,authType:'token',token:key,headerName:'Host'}));assert.throws(()=>manager.scope(['x'.repeat(101)]));const missing=createMCPConnections({directory:os.tmpdir(),safeStorage:{isEncryptionAvailable:()=>false}});await assert.rejects(missing.save({...base,authType:'token',token:key}),/加密/);});
test('authentication errors expose safe messages and clear verification',async t=>{let broken=false;const normal=mock([]);const {manager,server}=await setup(t,{fetchImpl:(...args)=>broken?new Response(key,{status:401}):normal(...args)});await manager.test(server.id);broken=true;await assert.rejects(manager.test(server.id),e=>e.code==='MCP_AUTH_REQUIRED'&&!e.message.includes(key));assert.equal((await manager.list())[0].connected,false);});
test('a stalled stream is cancelled by timeout and does not leave active operations',async t=>{let cancelled=false;const {manager,server}=await setup(t,{timeoutMs:25,fetchImpl:async()=>new Response(new ReadableStream({cancel(){cancelled=true;}}),{headers:{'content-type':'text/event-stream'}})});await assert.rejects(manager.test(server.id),/超时/);assert.equal(cancelled,true);assert.equal((await manager.list())[0].connected,false);});
test('disconnect cancels in-flight requests without stale verification overwriting it',async t=>{let started;const ready=new Promise(r=>started=r);const {manager,server}=await setup(t,{fetchImpl:async()=>{started();return new Response(new ReadableStream({}),{headers:{'content-type':'text/event-stream'}});}});const pending=manager.test(server.id);await ready;await manager.disconnect(server.id);await assert.rejects(pending,/断开/);const s=(await manager.list())[0];assert.equal(s.connected,false);assert.equal(s.enabled,false);});
test('permissions cannot change while approval is pending without aborting the call',async t=>{let started;const ready=new Promise(r=>started=r);const calls=[];const {manager,server}=await setup(t,{fetchImpl:mock(calls),confirmCall:async(_,signal)=>{started();await new Promise(resolve=>signal.addEventListener('abort',resolve,{once:true}));return true;}});await manager.test(server.id);const pending=manager.scope([server.id]).execute(call(server.id));await ready;await manager.permissions({id:server.id,permissions:{search_notes:'disabled'}});await assert.rejects(pending);assert.ok(!calls.some(c=>c.req.method==='tools/call'));});
test('tool lists reject duplicate definitions and looping cursors',async t=>{const calls=[];const {manager,server}=await setup(t,{fetchImpl:mock(calls,{tools:[tool,tool]})});await assert.rejects(manager.test(server.id),/重复/);});
test('custom MCP actions are advertised only for selected connections and named schema includes server ID',()=>{assert.ok(!allowedActions({phase:'chat'}).includes('mcp'));const state={phase:'chat',mcpConnections:[{id:'a'}]};assert.ok(allowedActions(state).includes('mcp'));assert.ok(actionTools(state).find(t=>t.function.name==='mcp').function.parameters.properties.id);});
test('Agent exposes only selected connections and can read tools without local artifacts',async t=>{const {manager,server,directory}=await setup(t,{confirmCall:async()=>true});await manager.test(server.id);const actions=[{action:'route',kind:'chat'},{action:'mcp',operation:'list',id:server.id},{action:'mcp',...call(server.id)},{action:'reply',text:'读取成功'}];const {runAgent}=require('../apps/desktop/agent/runner.cjs');const result=await runAgent({base:path.join(directory,'agent'),task:{id:'t',request:'读取笔记'},model:{contextWindow:32768},signal:new AbortController().signal,mcp:manager.scope([server.id]),ask:async messages=>{const state=JSON.parse(messages.at(-1).content);assert.deepEqual(state.mcpConnections.map(s=>s.id),[server.id]);assert.ok(!JSON.stringify(messages).includes(key));return {content:JSON.stringify(actions.shift())};}});assert.equal(result.content,'读取成功');assert.equal(result.agentRun.artifacts.length,0);});

test('uncertain writes remain blocked across restarts until the user resolves the specific record',async t=>{const calls=[],happy=mock(calls);let failCall=true;const fetchImpl=async(url,options)=>{if(JSON.parse(options.body).method==='tools/call'&&failCall){calls.push({req:JSON.parse(options.body)});throw Error('connection lost');}return happy(url,options);};const {manager,server,directory}=await setup(t,{fetchImpl,confirmCall:async()=>true});await manager.test(server.id);await assert.rejects(manager.scope([server.id]).execute(call(server.id)),{code:'MCP_RESULT_UNKNOWN'});const restarted=createMCPConnections({directory,safeStorage,fetchImpl,confirmCall:async()=>true});const pending=(await restarted.list())[0].pendingCalls;assert.equal(pending.length,1);await assert.rejects(restarted.scope([server.id]).execute(call(server.id)),{code:'MCP_RESULT_UNKNOWN'});assert.equal(calls.filter(c=>c.req.method==='tools/call').length,1);await restarted.resolveCall({id:server.id,callId:pending[0].id});failCall=false;await restarted.scope([server.id]).execute(call(server.id));assert.equal((await restarted.list())[0].pendingCalls.length,0);assert.equal(calls.filter(c=>c.req.method==='tools/call').length,2);});
test('disabled tools remain disabled when server definitions change',async t=>{let changed=false;const {manager,server}=await setup(t,{fetchImpl:(...args)=>mock([],{tools:[{...tool,description:changed?'changed':'查找笔记'}]})(...args)});await manager.test(server.id);await manager.permissions({id:server.id,permissions:{search_notes:'disabled'}});changed=true;await manager.test(server.id);assert.equal((await manager.list())[0].tools[0].permission,'disabled');});
test('tool pagination includes every page and looping cursors are rejected',async t=>{let looping=false;const base=mock([]);const {manager,server}=await setup(t,{fetchImpl:async(url,options)=>{const req=JSON.parse(options.body);if(req.method!=='tools/list')return base(url,options);return Response.json({jsonrpc:'2.0',id:req.id,result:req.params.cursor?{tools:looping?[]:[{...tool,name:'second'}],...(looping?{nextCursor:'same'}:{})}:{tools:[tool],nextCursor:'same'}});}});assert.equal((await manager.test(server.id)).tools.length,2);looping=true;await assert.rejects(manager.test(server.id),/分页无效/);});
