const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const JSZip=require('../apps/desktop/node_modules/jszip');
const {readMaterial,readSource,importPastedMaterials,extensions}=require('../apps/desktop/materials.cjs');
const {parseDocument}=require('../apps/desktop/document-parser.cjs');
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
function slide(text){return `<p:sld xmlns:p="${P}" xmlns:a="${A}"><p:cSld><p:spTree><p:sp><p:txBody><a:p><a:r><a:t>${text}</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:sld>`;}
async function fixture(dir){const z=new JSZip();z.file('ppt/presentation.xml',`<p:presentation xmlns:p="${P}" xmlns:r="${R}"><p:sldIdLst><p:sldId id="256" r:id="second"/><p:sldId id="257" r:id="first"/></p:sldIdLst></p:presentation>`);z.file('ppt/_rels/presentation.xml.rels',`<Relationships><Relationship Id="first" Target="slides/slide1.xml"/><Relationship Id="second" Target="slides/slide2.xml"/></Relationships>`);z.file('ppt/slides/slide1.xml',slide('第二页 &amp; 文本'));z.file('ppt/slides/slide2.xml',slide('第一页'));z.file('ppt/slides/_rels/slide2.xml.rels',`<Relationships><Relationship Id="note" Type="${R}/notesSlide" Target="../notesSlides/notesSlide7.xml"/></Relationships>`);z.file('ppt/notesSlides/notesSlide7.xml',`<p:notes xmlns:p="${P}" xmlns:a="${A}"><p:sp><p:nvSpPr><p:nvPr><p:ph type="sldNum"/></p:nvPr></p:nvSpPr><p:txBody><a:p><a:r><a:t>99</a:t></a:r></a:p></p:txBody></p:sp><p:sp><p:txBody><a:p><a:r><a:t>演讲备注</a:t></a:r></a:p></p:txBody></p:sp></p:notes>`);const file=path.join(dir,'方案.pptx');await fs.writeFile(file,await z.generateAsync({type:'nodebuffer'}));return {file,z};}
test('PPTX imports slides in presentation order with speaker notes and preserved originals',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-ppt-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const {file}=await fixture(dir);const parsed=await parseDocument(file);assert.equal(parsed.kind,'presentation');assert.equal(parsed.segments.length,2);assert.match(parsed.segments[0].text,/第一页\n\[演讲者备注\]\n演讲备注/);assert.doesNotMatch(parsed.text,/99/);assert.match(parsed.segments[1].text,/第二页 & 文本/);const material=await readMaterial(file);assert.equal(material.parseStatus,'parsed');const entries=await importPastedMaterials([{name:'方案.pptx',bytes:new Uint8Array(await fs.readFile(file))}],path.join(dir,'originals'));assert.ok(entries[0].sourceId);const original=await readSource(path.join(dir,'originals',entries[0].sourceId),'方案.pptx');assert.equal(original.text,parsed.text);assert.ok(extensions.includes('pptx')&&extensions.includes('ppt'));});
test('PPTX reports image-only pages and rejects malformed or unsafe XML',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-ppt-errors-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const {file,z}=await fixture(dir);z.file('ppt/slides/slide1.xml',slide(''));await fs.writeFile(file,await z.generateAsync({type:'nodebuffer'}));assert.equal((await parseDocument(file)).status,'partial');z.file('ppt/slides/slide1.xml','<!DOCTYPE sld [<!ENTITY x "unsafe">]>'+slide(''));await fs.writeFile(file,await z.generateAsync({type:'nodebuffer'}));await assert.rejects(parseDocument(file),/DTD/);await fs.writeFile(file,'not a presentation');await assert.rejects(readMaterial(file),/PPTX 无法读取/);});
test('legacy PPT is converted with an isolated LibreOffice profile when installed',async t=>{
 if(process.env.AILO_TEST_LIBREOFFICE!=='1'){t.skip('Set AILO_TEST_LIBREOFFICE=1 to test local conversion');return;}
 const binary='/opt/homebrew/bin/soffice';try{await fs.access(binary);}catch{t.skip('LibreOffice not installed');return;}
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ailo-ppt-legacy-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
 const z=new JSZip();z.file('mimetype','application/vnd.oasis.opendocument.presentation',{compression:'STORE'});z.file('META-INF/manifest.xml','<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.presentation"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>');z.file('content.xml','<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" office:version="1.2"><office:body><office:presentation><draw:page draw:name="page1"><draw:frame><draw:text-box><text:p>Legacy presentation token</text:p></draw:text-box></draw:frame></draw:page></office:presentation></office:body></office:document-content>');
 const file=path.join(dir,'legacy.odp');await fs.writeFile(file,await z.generateAsync({type:'nodebuffer'}));
 await new Promise((resolve,reject)=>require('node:child_process').execFile(binary,['-env:UserInstallation='+require('node:url').pathToFileURL(path.join(dir,'profile')).href,'--headless','--convert-to','ppt','--outdir',dir,file],{timeout:30000},e=>e?reject(e):resolve()));
 const parsed=await readMaterial(path.join(dir,'legacy.ppt'));assert.match(parsed.text,/Legacy presentation token/);assert.match(parsed.summary,/已转换旧版 PPT/);
});
